services:
  - type: web
    name: x-sevenai-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: PROJECT_NAME
        value: X-SevenAI
      - key: VERSION
        value: 1.0.0
      - key: API_V1_STR
        value: /api/v1
      - key: BACKEND_CORS_ORIGINS
        value: '["https://your-frontend-domain.com"]'
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: x-sevenai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: x-sevenai-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: x-sevenai-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: x-sevenai-redis
          property: connectionString
      # Add your API keys here (you'll need to set these manually in Render dashboard)
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false

  - type: pserv
    name: x-sevenai-db
    runtime: postgres
    ipAllowList: []  # Only accessible by other services in this project

  - type: redis
    name: x-sevenai-redis
    ipAllowList: []  # Only accessible by other services in this project
